<?php
/**
 * Created by PhpStorm.
 * User: dev30
 * Date: 11/29/16
 * Time: 1:53 PM
 *
 * Template for AlexDev_Zaproo_Block_QtyData
 *
 * @var $this AlexDev_Zaproo_Block_QtyData
 */

$products = $this->getProductsQtyData();
$display_type = $this->getData('type');
$is_empty_store = !($products->count() > 0);
?>

<?php if($is_empty_store) : ?>
    <p>Store is empty</p>
<?php else: ?>
    <table>
        <thead>
        <tr>
            <th>Product name</th>
            <th>SKU</th>
            <th>QTY</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($products as $product) : ?>
            <tr>
                <td><a href="<?=$product->getProductUrl() ?>"><?= $product->getName() ?></a></td>
                <td><?= $product->getSku() ?></td>
                <?php if ($display_type == AlexDev_Zaproo_IndexController::NUM_LIST) : ?>
                    <td><?= round($product->getQty(), 0)?></td>
                <?php elseif ($display_type == AlexDev_Zaproo_IndexController::STR_LIST) : ?>
                    <td><?= $product->getQty() > 0 ? 'In stock' : 'Out of stock'?></td>
                    <!--Or using isInStock()-->
                    <!--<td><?php//echo $product->isInStock() ? 'In stock' : 'Out of stock';?></td>-->
                <?php else : ?>
                    <td><?= round($product->getQty(), 0) . '&emsp;|&emsp;' . ($product->getQty() > 0 ? 'In stock' : 'Out of stock')?></td>
                    <!--<td><?php//echo round($product->getQty(), 0) . '&emsp;|&emsp;' . ($product->isInStock() ? 'In stock' : 'Out of stock')?></td>-->
                <?php endif;?>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
<?php endif; ?>