<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_articles = $this->getArticles(); ?>
    <div class="page-title article-title">
        <?php if(Mage::helper('zaproo/article')->isRssEnabled()) : ?>
            <a href="<?php echo Mage::helper('zaproo/article')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('zaproo')->__('Subscribe to RSS Feed')?></a>
        <?php endif;?>
        <h1><?php echo Mage::helper('zaproo')->__('Articles') ?></h1>
    </div>
<?php if ($_articles->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="article-list-container">
        <?php foreach ($_articles as $_article) : ?>
            <div class="article-list-item">
                <a href="<?php echo $_article->getArticleUrl()?>">
                    <?php echo $_article->getTitle();?>
                </a><br />
            </div>
        <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('zaproo')->__('There are no articles at this moment');?>
<?php endif;?>